# All the files we depend on. We are using a negative pattern to not include anything by accident.
# node_modules, packages (contains git submodules and node modules etc.), devnet dirs etc. all add up a lot.
*

!/cannon
!/op-alt-da
!/op-batcher
!/op-bindings
!/op-bootnode
!/op-chain-ops
!/op-challenger
!/op-core
!/packages/contracts-bedrock/snapshots
!/op-dispute-mon
!/op-conductor
!/op-heartbeat
!/op-node
!/op-preimage
!/op-program
!/op-proposer
!/op-service
!/op-supervisor
!/op-test-sequencer
!/op-wheel
!/op-plasma
!/go.mod
!/go.sum
