version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      day: "tuesday"
      time: "14:30"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "dependabot(gomod): "
    labels:
      - "M-dependabot"
