[book]
authors = ["Optimism Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Devnet SDK Book"

[output.html]
site-url = "/devnet-sdk/"
git-repository-url = "https://github.com/ethereum-optimism/optimism/tree/develop/devnet-sdk/book"
edit-url-template = "https://github.com/ethereum-optimism/optimism/tree/develop/devnet-sdk/book/{path}"
additional-css = ["custom.css", "theme/css/footer.css"]
additional-js = ["theme/js/footer.js"]
