codecov:
  require_ci_to_pass: false

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
  flags:
    - contracts-bedrock-tests

ignore:
  - "op-e2e"
  - "**/*.t.sol"
  - "packages/contracts-bedrock/test/**/*.sol"
  - "packages/contracts-bedrock/scripts/**/*.sol"
  - "packages/contracts-bedrock/src/vendor/**/*.sol"
  - "packages/contracts-bedrock/src/interfaces/**/*.sol"
  # TODO: add coverage for MIPS64 back once tests are merged in
  - "packages/contracts-bedrock/src/cannon/MIPS64.sol"
  - "packages/contracts-bedrock/src/cannon/libraries/MIPS64Instructions.sol"
  - "packages/contracts-bedrock/src/cannon/libraries/MIPS64State.sol"
  - "packages/contracts-bedrock/src/cannon/libraries/MIPS64Syscalls.sol"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      contracts:
        base: auto
        target: auto
        threshold: 5%
        informational: false
        flags:
          - contracts-bedrock-tests

flag_management:
  individual_flags:
    - name: contracts-bedrock-tests
      paths:
        - packages/contracts-bedrock/src
