FROM ghcr.io/foundry-rs/foundry:nightly-293fad73670b7b59ca901c7f2105bf7a29165a90

RUN apk add --no-cache jq
RUN apk add --update python3 py3-pip

COPY entrypoint-fork-l1.sh /entrypoint.sh
COPY fork-public-network.py /main.py

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
