FROM rust:latest

# Install necessary packages
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gnupg2 \
    lsb-release \
    software-properties-common

# Install Lighthouse dependencies
RUN apt-get install -y build-essential clang cmake libssl-dev pkg-config git

# Download pre-built Lighthouse binary
RUN wget https://github.com/sigp/lighthouse/releases/download/v5.1.3/lighthouse-v5.1.3-x86_64-unknown-linux-gnu.tar.gz \
    && tar -xzf lighthouse-v5.1.3-x86_64-unknown-linux-gnu.tar.gz \
    # && mv lighthouse /usr/local/bin/lighthouse \
    && rm lighthouse-v5.1.3-x86_64-unknown-linux-gnu.tar.gz

# Clone Lighthouse repository and build
# RUN git clone https://github.com/sigp/lighthouse.git \
#     && cd /lighthouse \
#     && git checkout v5.1.3 \
#     && cargo build --release

# Copy bootnode script, env files and bootnode binary
COPY entrypoint-bootnode.sh /entrypoint.sh
COPY vars.env /vars.env
COPY bin/bootnode /usr/local/bin/bootnode
COPY bin/lcli /usr/local/bin/lcli

# Copy built Lighthouse binary
# COPY /lighthouse/target/release/lighthouse /usr/local/bin/lighthouse

# change permission
RUN chmod +x /usr/local/bin/bootnode
RUN chmod +x /usr/local/bin/lcli
RUN chmod +x /entrypoint.sh
# RUN chmod +x /usr/local/bin/lighthouse

# Define entrypoint
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
