FROM rust:latest

# Install necessary packages
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gnupg2 \
    lsb-release \
    software-properties-common \
    jq

# Install Lighthouse dependencies
RUN apt-get install -y build-essential clang cmake libssl-dev pkg-config git

# Clone Lighthouse repository and build
RUN git clone https://github.com/sigp/lighthouse.git \
    && cd /lighthouse \
    && git checkout v5.1.3 \
    && make install-lcli

# copy files
COPY entrypoint-setup.sh /entrypoint.sh

# change permission
RUN chmod +x /entrypoint.sh

# entrypoint
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
