ARG L2_IMAGE=tokamaknetwork/thanos-op-geth:nightly-193382ee-amd64

FROM ${L2_IMAGE}

RUN apk add --no-cache jq

COPY entrypoint-l2.sh /entrypoint.sh

VOLUME ["/db"]

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
