[chain]
## Required ETL configuration which controls
## the rate and and range at data retrieval
l1-polling-interval = 5000 # 5s
l2-polling-interval = 5000

l1-header-buffer-size = 1000
l2-header-buffer-size = 1000

l1-confirmation-depth = 0 # unnecessary for devnet
l2-confirmation-depth = 0

### Option 1: Utilize a known preset for chain configuration
### See config/presets.go for available presets.
###    i.e OP, Base, Zora, PGN, etc.
preset = 901 # Local Devnet

### Option 2: Custom Networks
###
### Deployment block height of the rollup. Must be set
### correctly otherwise the ETL will start from L1
### genesis resulting in a lot of wasted work. Confirmation
### depths should be set appropriately to avoid a the ETL
### getting stuck terminally due to a reorg
# l1-starting-height = 0
#
# l1-confirmation-depth = 10
# l2-confirmation-depth = 75 (roughly 10 L1 block equivalent)
#
### These contract addresses MUST be the Proxy contract
### addresses and not the implementation
# [chain.l1-contracts]
# address-manager = ""
# system-config = ""
# optimism-portal = ""
# l2-output-oracle = ""
# l1-cross-domain-messenger = ""
# l1-standard-brigde = ""
# l1-erc721-bridge = ""
###

[rpcs]
l1-rpc = "${INDEXER_L1_RPC_URL}"
l2-rpc = "${INDEXER_L2_RPC_URL}"

[db]
host = "${DB_HOST}"
port = ${DB_PORT}
user = "${DB_USER}"
password = "${DB_PWD}"
name = "${DB_NAME}"

[http]
host = "0.0.0.0"
port = 8100
timeout = 10

[metrics]
host = "0.0.0.0"
port = 7300
