package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/ethereum/go-ethereum/log"
	"github.com/tokamak-network/tokamak-thanos/op-chain-ops/foundry"
	"github.com/tokamak-network/tokamak-thanos/op-chain-ops/genesis"
)

// initTokamakAllocType initializes the configuration for a specific AllocType
// using Tokamak's deployment approach
func initTokamakAllocType(root string, allocType AllocType) error {
	log.Info("Initializing Tokamak alloc type", "allocType", allocType)

	// 1. Load state-dump files (generated by Python script)
	statePath := getStatePathForAllocType(root, allocType)

	// Check if state-dump file exists
	if _, err := os.Stat(statePath); err == nil {
		// Load L1 allocs from state-dump
		l1Allocs, err := foundry.LoadForgeAllocs(statePath)
		if err != nil {
			return fmt.Errorf("failed to load L1 allocs from %s: %w", statePath, err)
		}

		mtx.Lock()
		l1AllocsByType[allocType] = l1Allocs
		mtx.Unlock()

		log.Info("Loaded L1 allocs from state-dump", "path", statePath)
	} else {
		log.Warn("State-dump file not found, will use deployment addresses only", "path", statePath)
	}

	// 2. Load deployment addresses from .deploy file
	l1Deployments, err := LoadTokamakDeployment(root)
	if err != nil {
		// If .deploy file doesn't exist, create minimal deployments
		log.Warn("Failed to load deployments, using minimal config", "error", err)
		l1Deployments = createMinimalDeployments()
	}

	// 3. Override with Tokamak-specific addresses if needed
	overrideTokamakAddresses(l1Deployments)

	mtx.Lock()
	l1DeploymentsByType[allocType] = l1Deployments
	mtx.Unlock()

	// 4. Load deploy config
	deployConfigPath := path.Join(root, "packages/tokamak/contracts-bedrock/deploy-config/devnetL1.json")
	deployConfig, err := loadDeployConfig(deployConfigPath)
	if err != nil {
		log.Warn("Failed to load deploy config, using defaults", "error", err)
		deployConfig = createDefaultDeployConfig()
	}

	mtx.Lock()
	deployConfigsByType[allocType] = deployConfig
	mtx.Unlock()

	// 5. Handle L2 allocs for different hardforks
	l2AllocsMap := make(genesis.L2AllocsModeMap)

	// For each hardfork mode, try to load the corresponding L2 alloc file
	modes := []genesis.L2AllocsMode{
		genesis.L2AllocsDelta,
		genesis.L2AllocsEcotone,
		genesis.L2AllocsFjord,
		genesis.L2AllocsGranite,
		genesis.L2AllocsHolocene,
		genesis.L2AllocsIsthmus,
		genesis.L2AllocsInterop,
	}

	for _, mode := range modes {
		l2AllocPath := getL2AllocPathForMode(root, mode)
		if _, err := os.Stat(l2AllocPath); err == nil {
			l2Allocs, err := foundry.LoadForgeAllocs(l2AllocPath)
			if err != nil {
				log.Warn("Failed to load L2 allocs", "mode", mode, "path", l2AllocPath, "error", err)
				continue
			}
			l2AllocsMap[mode] = l2Allocs
			log.Info("Loaded L2 allocs", "mode", mode, "accounts", len(l2Allocs.Accounts))
		}
	}

	// If no specific mode files found, try the generic l2-allocs.json
	if len(l2AllocsMap) == 0 {
		genericL2Path := path.Join(root, "packages/tokamak/contracts-bedrock/l2-allocs.json")
		if _, err := os.Stat(genericL2Path); err == nil {
			l2Allocs, err := foundry.LoadForgeAllocs(genericL2Path)
			if err == nil {
				// Use this for all modes
				for _, mode := range modes {
					l2AllocsMap[mode] = l2Allocs
				}
				log.Info("Loaded generic L2 allocs for all modes", "accounts", len(l2Allocs.Accounts))
			}
		}
	}

	mtx.Lock()
	l2AllocsByType[allocType] = l2AllocsMap
	mtx.Unlock()

	log.Info("Tokamak alloc type initialized", "allocType", allocType, "l2_modes", len(l2AllocsMap))
	return nil
}

// getL2AllocPathForMode returns the path to L2 alloc file for a given mode
func getL2AllocPathForMode(root string, mode genesis.L2AllocsMode) string {
	base := path.Join(root, "packages/tokamak/contracts-bedrock")
	
	switch mode {
	case genesis.L2AllocsDelta:
		return path.Join(base, "l2-allocs-delta.json")
	case genesis.L2AllocsEcotone:
		return path.Join(base, "l2-allocs-ecotone.json")
	default:
		return path.Join(base, "l2-allocs.json")
	}
}

// getStatePathForAllocType returns the path to the state-dump file for a given AllocType
func getStatePathForAllocType(root string, allocType AllocType) string {
	base := path.Join(root, "packages/tokamak/contracts-bedrock")

	switch allocType {
	case AllocTypeMTCannon, AllocTypeMTCannonNext:
		return path.Join(base, "state-dump-901.json")
	case AllocTypeAltDA:
		return path.Join(base, "state-dump-901.json")
	default:
		return path.Join(base, "state-dump-901.json")
	}
}

// getL2StatePathForMode returns the path to the L2 state-dump file for a given mode
func getL2StatePathForMode(root string, allocType AllocType, mode genesis.L2AllocsMode) string {
	base := path.Join(root, "packages/tokamak/contracts-bedrock")

	switch mode {
	case genesis.L2AllocsDelta:
		return path.Join(base, "state-dump-901-delta.json")
	case genesis.L2AllocsEcotone:
		return path.Join(base, "state-dump-901-ecotone.json")
	default:
		return path.Join(base, "state-dump-901.json")
	}
}

// overrideTokamakAddresses overrides addresses with Tokamak-specific values
func overrideTokamakAddresses(deployments *genesis.L1Deployments) {
	// Add any Tokamak-specific address overrides here
	// For example, L2NativeToken, L1UsdcBridge, etc.
	// These are already loaded from .deploy file, so might not need overrides
}

// loadDeployConfig loads the deploy config from a JSON file
func loadDeployConfig(path string) (*genesis.DeployConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read deploy config: %w", err)
	}

	var config genesis.DeployConfig
	if err := json.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to unmarshal deploy config: %w", err)
	}

	return &config, nil
}

// createDefaultDeployConfig creates a minimal default deploy config
func createDefaultDeployConfig() *genesis.DeployConfig {
	// Create an empty deploy config with nested structs initialized
	config := &genesis.DeployConfig{}
	// The actual fields are in nested structs, not direct fields
	// Most values will be zero/empty which is fine for minimal testing
	return config
}

// createMinimalDeployments creates minimal L1 deployments for testing
func createMinimalDeployments() *genesis.L1Deployments {
	return &genesis.L1Deployments{
		// Set minimal addresses for testing
		// These will be overridden when actual deployment is available
	}
}

// InitTokamakConfig initializes all Tokamak configurations
func InitTokamakConfig(root string) error {
	log.Info("Initializing Tokamak E2E configuration")

	// Initialize all alloc types SEQUENTIALLY to avoid conflicts
	// (Previously used parallel execution but it caused EVM state conflicts)
	for _, allocType := range allocTypes {
		if err := initTokamakAllocType(root, allocType); err != nil {
			return fmt.Errorf("failed to init %s: %w", allocType, err)
		}
	}

	log.Info("Tokamak E2E configuration initialized successfully")
	return nil
}
