name: Check JS lint

on:
  push:
jobs:
  pnpm-monorepo:
    runs-on: ubuntu-latest
    container:
      image: onthertech/titan-ci-builder:latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: restore_cache
      uses: actions/cache@v3.3.2
      with:
        key: pnpm-packages-v2-{{ checksum "pnpm-lock.yaml" }}
        path: node_modules
        restore-keys: pnpm-packages-v2-{{ checksum "pnpm-lock.yaml" }}
    - name: Fetch dependencies
      run: pnpm fetch --frozen-lockfile --prefer-offline
    - name: Install dependencies
      run: pnpm install --frozen-lockfile --offline
    - name: print forge version
      run: forge --version
    - name: Build monorepo
      run: pnpm build
    - uses: actions/upload-artifact@v4.0.0
      with:
        path: |-
          ./packages/**/dist
          ./packages/contracts-bedrock/forge-artifacts
  js-lint-test:
    runs-on: ubuntu-latest
    container:
      image: onthertech/titan-ci-builder:latest
    needs:
    - pnpm-monorepo
    env:
      name: chain-mon-tests
      coverage_flag: chain-mon-tests
      package_name: chain-mon
      dependencies: "(common-ts|contracts-bedrock|core-utils|sdk)"
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v4.1.0
      with:
        path: "."
    - name: restore_cache
      uses: actions/cache@v3.3.2
      with:
        key: pnpm-packages-v2-{{ checksum "pnpm-lock.yaml" }}
        path: node_modules
        restore-keys: pnpm-packages-v2-{{ checksum "pnpm-lock.yaml" }}
    - uses: "./.github/actions/check-changed"
      with:
        patterns: "${{ env.package_name }}, ${{ env.dependencies }}"
    - name: Lint
      run: pnpm lint && git diff --exit-code
      working-directory: packages/${{ env.package_name }}
    - name: Test
      run: pnpm test:coverage
      working-directory: packages/${{ env.package_name }}
    - name: Upload coverage
      run: codecov --verbose --clean --flags ${{ env.coverage_flag }}