name: 'Contract Bedrock Test'
on:
  push:
    paths:
      - 'op-node/**'
jobs:
  contracts-bedrock-tests:
    name: "Contract bedrock test"
    runs-on: ubuntu-latest
    container:
      image: onthertech/titan-ci-builder:latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/check-changed"
      with:
        patterns: packages/contracts-bedrock
    - name: Fetch dependencies
      run: pnpm fetch --frozen-lockfile --prefer-offline
    - name: Install dependencies
      run: pnpm install --frozen-lockfile --offline
    - name: print forge version
      run: forge --version
      working-directory: packages/contracts-bedrock
    - name: run tests
      run: echo 'test'