name: Check Go lint

on:
  push:
jobs:
  go-lint:
    runs-on: ubuntu-latest
    container:
      image: onthertech/titan-ci-builder:latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Setup Go
      uses: actions/setup-go@v4
    - name: Go mod tidy
      run: make mod-tidy && git diff --exit-code
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
        args: -E goimports,sqlclosecheck,bodyclose,asciicheck,misspell,errorlint --timeout 5m -e "errors.As" -e "errors.Is" ./...
      env:
        GOFLAGS: "-buildvcs=false"