name: Check JS lint

on:
  push:
jobs:
  pnpm-monorepo:
    runs-on: ubuntu-latest
    container:
      image: onthertech/titan-ci-builder:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Restore PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fetch dependencies
        run: pnpm fetch --frozen-lockfile --prefer-offline

      - name: Save PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --offline

      - name: Print forge version
        run: forge --version

      - name: Build monorepo
        run: pnpm build

      - name: Persist to workspace
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: |
            packages/**/dist
            packages/contracts-bedrock/forge-artifacts

  js-lint-test:
    runs-on: ubuntu-latest
    needs: [pnpm-monorepo]
    container:
      image: onthertech/titan-ci-builder:latest
    name: js-lint-test-${{matrix.params.name}}

    strategy:
      matrix:
        params: [
          {
            name: 'common-ts-tests',
            package_name: 'common-ts',
            coverage_flag: 'common-ts-tests'
          },
          {
            name: 'core-utils-tests',
            package_name: 'core-utils',
            coverage_flag: 'core-utils-tests'
          },
          {
            name: 'chain-mon-tests',
            package_name: 'chain-mon',
            dependencies: '(common-ts|contracts-bedrock|core-utils|sdk)',
            coverage_flag: 'chain-mon-tests'
          },
          {
            name: 'contracts-ts-tests',
            package_name: 'contracts-ts',
            dependencies: '(contracts-bedrock|contracts-ts)',
            coverage_flag: 'contracts-ts-tests'
          },
          {
            name: 'sdk-next-tests',
            package_name: 'sdk',
            dependencies: '(common-ts|contracts-bedrock|core-utils)',
            coverage_flag: 'sdk-next-tests'
          },
          {
            name: 'sdk-tests',
            package_name: 'sdk',
            dependencies: '(contracts-bedrock|core-utils)',
            coverage_flag: 'sdk-tests'
          }
        ]

    env:
      package_name: ${{ matrix.params.package_name }}
      dependencies: ${{ matrix.params.dependencies }}
      coverage_flag: ${{ matrix.params.coverage_flag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Check changes
        uses: "./.github/actions/check-changed"
        with:
          patterns: "${{ env.package_name }},${{ env.dependencies }}"
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: "."
      - name: Restore PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint
        run: pnpm lint && git diff --exit-code
        working-directory: packages/${{ env.package_name }}

      - name: Test
        run: pnpm test:coverage
        working-directory: packages/${{ env.package_name }}

      - name: Upload coverage
        run: codecov --verbose --clean --flags ${{ env.coverage_flag }}