name: Check JS lint

on:
  pull_request:
    paths:
      - 'packages/**/*.ts'
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          common-ts:
            - 'packages/common-ts/**'
          core-utils:
            - 'packages/core-utils/**'
          contracts-ts:
            - 'packages/contracts-ts/**'
          sdk:
            - 'packages/sdk/**'
            - name: Checkout
    - name: Echo JSON
      run: echo ${{ toJson(steps.filter.outputs.changes)}}
    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - if: ${{ toJson(steps.filter.outputs.changes)}} != '[]'
      name: Restore PNPM Package Cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

    - if: ${{ toJson(steps.filter.outputs.changes)}} != '[]'
      name: Fetch dependencies
      run: pnpm fetch --frozen-lockfile --prefer-offline

    - if: ${{ toJson(steps.filter.outputs.changes)}} != '[]'
      name: Save PNPM Package Cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

    - if: ${{ toJson(steps.filter.outputs.changes)}} != '[]'
      name: Install dependencies
      run: pnpm install --frozen-lockfile --offline

  js-lint-test:
    runs-on: ubuntu-latest
    needs: [changes]
    container:
      image: onthertech/titan-ci-builder:latest
    name: js-lint-test-${{matrix.package}}

    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}

    steps:
      - name: Print needs
        run: echo ${{fromJSON(needs.changes.outputs.packages)}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Restore PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Lint
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          cd packages/${{ matrix.package }}
          pnpm lint && git diff --exit-code

