name: Check JS lint

on:
  pull_request:
    paths:
      - 'packages/**/*.ts'
jobs:
  pnpm-monorepo:
    runs-on: ubuntu-latest
    container:
      image: onthertech/titan-ci-builder:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Restore PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fetch dependencies
        run: pnpm fetch --frozen-lockfile --prefer-offline

      - name: Save PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --offline

      - name: Print forge version
        run: forge --version

  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          common-ts:
            - 'packages/common-ts/**'
          core-utils:
            - 'packages/core-utils/**'
          contracts-ts:
            - 'packages/contracts-ts/**'
          sdk:
            - 'packages/sdk/**'

  js-lint-test:
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.packages == 'true' }}
    needs: [changes,pnpm-monorepo]
    container:
      image: onthertech/titan-ci-builder:latest
    name: js-lint-test-${{matrix.package}}

    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Restore PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Lint
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          cd packages/${{ matrix.package }}
          pnpm lint && git diff --exit-code

