name: Publish genesis and rollup file

on:
  push:
    paths:
      - 'packages/tokamak/contracts-bedrock/genesis/**'
  workflow_dispatch:

jobs:
  publish-genesis-rollup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'packages/tokamak/contracts-bedrock/genesis'
