name: 'E2E Runner Test'
on:
  push:
    branches:
      - OR-1586-change-runners-to-e2e-tests

jobs:
  build:
    runs-on: onther4
    container:
        image: onthertech/thanos-ci-builder:latest
    steps:
      - name: Check CPUs
        run: lscpu && echo
  
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Run a one-line script
        run: echo Hello, world!
