name: 'Tokamak Contract Bedrock Test'
on:
  pull_request:
    paths:
      - 'op-node/**'
      - 'packages/tokamak/contracts-bedrock/**'

jobs:
  contracts-bedrock-tests:
    name: 'Contract Bedrock test'
    runs-on: ubuntu-latest
    container:
      image: tokamaknetwork/thanos-ci-builder:ecotone
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Restore PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Fetch dependencies
        run: pnpm fetch --frozen-lockfile --prefer-offline

      - name: Save PNPM Package Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --offline

      - name: Print forge version
        run: forge --version
        working-directory: packages/tokamak/contracts-bedrock

      - name: Run pnpm test
        run: pnpm test
        working-directory: packages/tokamak/contracts-bedrock
