name: 'Tokamak Contract Bedrock Test'
on:
  push:
    branches:
      - OR-1586-change-runners-to-e2e-tests

jobs:
  contracts-bedrock-tests:
    name: 'Contract Bedrock test'
    runs-on: onther4
    container:
      image: onthertech/thanos-ci-builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Restore Node Modules
        uses: actions/cache@v3.3.2
        with:
          key: pnpm-packages-v2-{{ checksum "pnpm-lock.yaml" }}
          path: node_modules
          restore-keys: pnpm-packages-v2-{{ checksum "pnpm-lock.yaml" }}

      - name: Fetch dependencies
        run: pnpm fetch --frozen-lockfile --prefer-offline

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --offline

      - name: Print forge version
        run: forge --version
        working-directory: packages/tokamak/contracts-bedrock

      - name: Run pnpm test
        run: pnpm test
        working-directory: packages/tokamak/contracts-bedrock
